return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    dashboard = { enabled = true },
    indent = {
      animate = { enabled = false },
    },
    lazygit = { enabled = true },
    gitbrowser = { enabled = true },
    input = { enabled = true },
    notifier = { enabled = true },
    picker = { enabled = true },
    quickfile = { enabled = true },
    scope = { enabled = true },
    toggle = { enabled = true },
    statuscolumn = { enabled = true },
    words = { enabled = true },
  },
  keys = {
    { "<leader>gg",  function() Snacks.lazygit() end,                                       desc = "Lazygit" },
    { "<leader>pf",  function() Snacks.picker.files() end,                                  desc = "Snacks.Picker project files" },
    { "<C-p>",       function() Snacks.picker.git_files() end,                              desc = "Snacks.Picker git files" },
    { "<leader>ps",  function() Snacks.picker.grep() end,                                   desc = "Snacks.Picker live grep" },
    { "<leader>fh",  function() Snacks.picker.help() end,                                   desc = "Snacks.Picker search help" },
    { "<leader>fb",  function() Snacks.picker.buffers() end,                                desc = "Snacks.Picker search buffers" },
    { "<leader>fdd", function() Snacks.picker.diagnostics({ bufnr = 0 }) end,               desc = "Snacks.Picker search document diagnostics" },
    { "<leader>fds", function() Snacks.picker.lsp_symbols() end,                            desc = "Snacks.Picker search document symbols" },
    { "<leader>fwd", function() Snacks.picker.diagnostics() end,                            desc = "Snacks.Picker search workspace diagnostics" },
    { "<leader>fws", function() Snacks.picker.lsp_workspace_symbols() end,                  desc = "Snacks.Picker search workspace symbols" },
    { "<leader>en",  function() Snacks.picker.files { cwd = vim.fn.stdpath("config") } end, desc = "Snacks.Picker nvim config files" },
  }
}
